# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - master

pr:
  - master

pool:
  vmImage: 'macos-latest'

steps:
  - bash: sh start-emulator.sh
    displayName: Start emulator

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean check connectedCheck --stacktrace'